[package]
name = "sa-base-db"
version = "0.1.3"
edition = "2024"

[dependencies]
salsa = "0.25"
sa-config = { path = "../sa-config" }
sa-project-model = { path = "../sa-project-model" }
sa-paths = { path = "../sa-paths" }
sa-vfs = { path = "../sa-vfs" }

[lib]
path = "src/lib.rs"
