[package]
name = "sa-syntax"
version = "0.1.4"
edition = "2024"

[dependencies]
sa-span = { path = "../sa-span" }
solar-ast = { workspace = true }
solar-data-structures = { workspace = true }
solar-interface = { workspace = true }
solar-parse = { workspace = true }

[lib]
path = "src/lib.rs"
